# fly.toml app configuration file generated for svelte-mostly-official-tutorial on 2023-09-22T16:52:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "svelte-mostly-official-tutorial"
primary_region = "dfw"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
